//===-------- KudeyarSubtarget.h ---------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
// Year: 2017
// Alexey Shistko     alexey@kudeyar.com
// Andrei Safronov    andrei@kudeyar.com
//===----------------------------------------------------------------------===//
#ifndef LLVM_TARGET_KUDEYAR_SUBTARGET_H
#define LLVM_TARGET_KUDEYAR_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "KudeyarGenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class KudeyarSubtarget : public KudeyarGenSubtargetInfo 
{
  virtual void anchor();
  bool ExtendedInsts;
public:
  /// This constructor initializes the data members to match that
  /// of the specified triple.
  ///
  KudeyarSubtarget(const std::string &TT, const std::string &CPU,
                  const std::string &FS);

  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);

  bool isLinux() const { return false; }
};
} // End llvm namespace

#endif  /* LLVM_TARGET_KUDEYAR_SUBTARGET_H */
